version: "3"

services:
  ## MQTT for communication
  mqtt:
    image: eclipse-mosquitto
    container_name: ayoti_mqtt
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      mqtt_network:

  ## AGENT from schema
  fake_agent:
    container_name: ayoti_agent
    build: ./agent
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      MQTT_PARKING_TOPIC: "parking_data_topic"
      DELAY: 0.1
    networks:
      mqtt_network:
  
  ## PG for saving data
  postgres_db:
    image: postgres:latest
    container_name: ayoti_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql"
    ports:
      - "5432:5432"
    networks:
      db_network:

  # PGADMIN to view postgres with UI
  pgadmin:
    container_name: ayoti_pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      db_network:

  # STORE from schema
  store:
    container_name: ayoti_store
    build: ./store
    depends_on:
      - postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      db_network:

  ## REDIS for HUB
  redis:
    image: redis:latest
    container_name: ayoti_redis
    ports:
      - "6379:6379"
    networks:
      hub_redis:

  ## HUB from schema
  hub:
    container_name: ayoti_hub
    build: ./hub
    depends_on:
      - mqtt
      - redis
      - store
    environment:
      STORE_API_HOST: "store"
      STORE_API_PORT: 8000


networks:
  mqtt_network:
  db_network:
  hub_redis:

volumes:
  postgres_data:
  pgadmin-data: