version: "3"

services:
  # PG for storing data
  postgres_db:
    image: postgres:latest
    container_name: ayoti_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      db_network:

  # PgAdmin - UI for PG
  pgadmin:
    container_name: ayoti_pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      db_network:

  # Redis for hub
  redis:
    image: redis:latest
    container_name: ayoti_redis
    ports:
      - "6379:6379"
    networks:
      hub_redis:

  # Store from schema
  store:
    container_name: ayoti_store
    build: ./store
    depends_on:
      - postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    networks:
      hub_store:
      db_network:
      hub:

networks:
  mqtt_network:
  db_network:
  edge_hub:
  hub:
  hub_store:
  hub_redis:

volumes:
  postgres_data:
  pgadmin-data:
